---
name: Run light test suite on Koha code

on:
  workflow_call:
    inputs:
      arch:
        default: 'amd64'
        type: string
      project:
        default: 'koha-testing-workflow'
        type: string

jobs:
  run-light-tests:
    name: ${{ inputs.project }} - Run light test suite
    runs-on:
      - bare-metal
      - ${{ inputs.arch }}
    if: ${{ !cancelled() && (!join(needs.*.result, ',') || contains(join(needs.*.result, ','), 'success')) }}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - run: |
             set -x
             export HELPER_SCRIPT="$(mktemp -d -p /tmp helper-script-XXXXXX)"
             echo HELPER_SCRIPT="$HELPER_SCRIPT" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             export SYNC_REPO="${{ env.FORGEJO_WORKSPACE }}"
             echo SYNC_REPO="$SYNC_REPO" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             export KOHA_AUTO_VERSION="$(perl -I. -MKoha -le 'print $Koha::VERSION' | cut -b 1-5)"

             # unsupported versions
             [[ "$KOHA_AUTO_VERSION" == *".06"* ]] && KOHA_AUTO_VERSION="main"
             [[ "$KOHA_AUTO_VERSION" == *".12"* ]] && KOHA_AUTO_VERSION="main"

             [ -z "$KOHA_VERSION" ] && KOHA_VERSION="$KOHA_AUTO_VERSION"
             echo KOHA_VERSION="$KOHA_VERSION" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             [ -z "$KOHA_IMAGE" ] && KOHA_IMAGE="${{ env.KOHA_VERSION }}-bookworm"
             export KOHA_IMAGE="$KOHA_IMAGE"
             echo KOHA_IMAGE="$KOHA_IMAGE" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             ## todo: forgejo_actions has custom code, mainline it
             curl -o "${{ env.HELPER_SCRIPT }}/koha_tests_runner.pl" -f \
                 "https://forgejo.openfifth.co.uk/openfifth/jenkins-helper-scripts/raw/branch/forgejo_actions/koha_tests_runner.pl?inline=false"
      - run: |
             set -x
             [ -z "$DB_IMAGE" ] && DB_IMAGE="mariadb:10.11"

             perl "${{ env.HELPER_SCRIPT }}/koha_tests_runner.pl" \
                 --initial-docker-cleanup \
                 --run-light-test-suite \
                 --warmup-timeout 1200 \
                 --force-cleanup \
                 --verbose
        timeout-minutes: 360
      - uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-taps
          path: |
                ${{ env.FORGEJO_WORKSPACE }}/junit_main.xml
                ${{ env.FORGEJO_WORKSPACE }}/junit-cypress-*.xml
                ${{ env.FORGEJO_WORKSPACE }}/cover_db/*.xml
        if: success() || failure()
      - run: |
             set -x
             [ -d "$HELPER_SCRIPT" ] && rm -rfv "$HELPER_SCRIPT"
        if: success() || failure()

  analyse-light-tests:
    name: ${{ inputs.project }} - Analyse results of light test suite run
    runs-on:
      - bare-metal
      - ${{ inputs.arch }}
    needs:
      - run-light-tests
    if: ${{ !cancelled() && (needs.run-light-tests.result == 'success' || needs.run-light-tests.result == 'failure') }}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-taps
      - uses: https://github.com/test-summary/action@v2
        with:
          paths: ${{ env.FORGEJO_WORKSPACE }}/*.xml
          output: ${{ env.FORGEJO_WORKSPACE }}/test-summary.md
          show: fail,skip
      - run: |
             ISSUE_TITLE="[forgejo-actions] Run ${{ env.FORGEJO_RUN_NUMBER }} on ${{ env.FORGEJO_REF }} – Test summary"
             ISSUE_BODY="$(cat '${{ env.FORGEJO_WORKSPACE }}/test-summary.md' | perl -pe 's/\"/\\"/g' | perl -pe 's/\n/\\n/g')"

             curl -X POST -f \
                 "${{ env.FORGEJO_API_URL }}/repos/${{ env.FORGEJO_REPOSITORY }}/issues" \
                 -H "accept: application/json" \
                 -H "Authorization: Token ${{ env.FORGEJO_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "{\"title\":\"$ISSUE_TITLE\",\"closed\":true,\"body\":\"$ISSUE_BODY\"}" >/dev/null

             echo -ne "[INFO]\tAn issue has been created with a summary of this test suite's status\n"
             echo -ne "[INFO]\tPlease go to ${{ env.FORGEJO_SERVER_URL }}/${{ env.FORGEJO_REPOSITORY }}/issues\n"
             echo -ne "[INFO]\tThe issues will be titled with this checkout ref and run number, in closed issues\n"
      - uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-summary
          path: |
                ${{ env.FORGEJO_WORKSPACE }}/test-summary.md
        if: success() || failure()