---
name: Run light test suite on Koha code

on:
  workflow_call:
    inputs:
      arch:
        default: 'amd64'
        type: string
      project:
        default: 'koha-testing-workflow'
        type: string

jobs:
  run-light-tests:
    name: ${{ inputs.project }} - Run light test suite
    runs-on:
      - bare-metal
      - ${{ inputs.arch }}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - run: |
             set -x
             export JENKINS_HELPER_SCRIPTS="$(mktemp -d -p /tmp jenkins-helper-script-XXXXXX)"
             echo JENKINS_HELPER_SCRIPTS="$JENKINS_HELPER_SCRIPTS" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             export SYNC_REPO="${{ env.FORGEJO_WORKSPACE }}"
             echo SYNC_REPO="$SYNC_REPO" >> ${{ env.FORGEJO_ENV }}
      - run: |
             set -x
             git clone --branch forgejo_actions --single-branch --depth 1 "https://forgejo.openfifth.co.uk/openfifth/jenkins-helper-scripts.git" "$JENKINS_HELPER_SCRIPTS"
      - run: |
             set -x
             [ -z "$KOHA_IMAGE" ] && KOHA_IMAGE="main"
             [ -z "$DB_IMAGE" ] && DB_IMAGE="mariadb:10.11"

             perl "$JENKINS_HELPER_SCRIPTS/koha_tests_runner.pl" \
                 --initial-docker-cleanup \
                 --run-light-test-suite \
                 --warmup-timeout 550 \
                 --force-cleanup \
                 --verbose
        timeout-minutes: 360
      - uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-taps
          path: |
                ${{ env.FORGEJO_WORKSPACE }}/junit_main.xml
                ${{ env.FORGEJO_WORKSPACE }}/junit-cypress-*.xml
                ${{ env.FORGEJO_WORKSPACE }}/cover_db/*.xml
      - run: |
             set -x
             [ -d "$JENKINS_HELPER_SCRIPTS" ] && rm -rfv "$JENKINS_HELPER_SCRIPTS"
        if: success() || failure()

  analyse-light-tests:
    name: ${{ inputs.project }} - Analyse results of light test suite run
    runs-on:
      - bare-metal
      - ${{ inputs.arch }}
    needs:
      - run-light-tests
    if: ${{ !cancelled() && !failure() }}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-taps
      - uses: https://github.com/test-summary/action@v2
        with:
          paths: ${{ env.FORGEJO_WORKSPACE }}/*.xml
          output: ${{ env.FORGEJO_WORKSPACE }}/test-summary.md
          show: fail,skip
      - run: |
             ISSUE_TITLE="[forgejo-actions] Run ${{ env.FORGEJO_RUN_NUMBER }} on ${{ env.FORGEJO_REF }} – Test summary"
             ISSUE_BODY="$(cat '${{ env.FORGEJO_WORKSPACE }}/test-summary.md' | perl -pe 's/\"/\\"/g' | perl -pe 's/\n/\\n/g')"

             curl -X POST \
                 "${{ env.FORGEJO_API_URL }}/repos/${{ env.FORGEJO_REPOSITORY }}/issues" \
                 -H "accept: application/json" \
                 -H "Authorization: Token ${{ env.FORGEJO_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "{\"title\":\"$ISSUE_TITLE\",\"closed\":true,\"body\":\"$ISSUE_BODY\"}" >/dev/null

             echo -ne "[INFO]\tAn issue has been created with a summary of this test suite's status\n"
             echo -ne "[INFO]\tPlease go to ${{ env.FORGEJO_SERVER_URL }}/${{ env.FORGEJO_REPOSITORY }}/issues\n"
             echo -ne "[INFO]\tThe issues will be titled with this checkout ref and run number, in closed issues\n"
      - uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: ${{ inputs.project }}-light-test-suite-summary
          path: |
                ${{ env.FORGEJO_WORKSPACE }}/test-summary.md
